### ISSUE TITLE
Support highlighting in script tags

### ISSUE THREAD

**Issue by LarsDenBakker** [mjbvz/vscode-lit-html#13]
Currently syntax highlighting only works inside .js files. It would be great if it could also support highlighting inside <script> tags inside .html files.

**Comment by mjbvz** [comment]
I think we can add syntax highlighing easily enough but adding full intellisense for html inside of script blocks is out of scope (the reason being that `<script>` IntelliSense is managed by VS Code's html extension currently)

If anyone wants to implement this, we'd basically just need [another injection](https://github.com/mjbvz/vscode-lit-html/blob/master/package.json#L33) that targets the `script` scope in html files

**Comment by vdegenne** [comment]
One year after : Is it possible to reopen this issue ?

I write a lot of code for web development and sometimes I like to just pop `lit-html` in a `type="module"` script tag.

If you think that might cause a conflict, why not implementing an option for the `settings.json` file ?
