### ISSUE TITLE
Build tag name completions from HTMLElementTagNameMap

### ISSUE THREAD

**Issue by justinfagnani** [mjbvz/vscode-lit-html#20]
When writing custom elements it's possible to add their name and class to the type system via HTMLElementTagNameMap:

```ts
/** A test element */
export class XFoo extends HTMLElement {}

declare global {
  interface HTMLElementTagNameMap {
    'x-foo': XFoo;
  }
}
```

It's be great if tag name completion and documentation came from the keys and values of HTMLElementTagNameMap.

Even better would be if we standardized on some JSDoc annotations for describing attributes for attribute completion:

```ts
/** 
 * A test element
 * @attribute bar The description of the bar attribute.
 */
export class XFoo extends HTMLElement {}
```

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/typescript-lit-html-plugin/issues/5
