### ISSUE TITLE
Tag pattern settings to override the default begin pattern

### ISSUE THREAD

**Issue by jtr109** [mjbvz/vscode-lit-html#25]
The extension is great. But in my case, I desired a custom tag pattern. Sometimes, I need a pattern to render html like below:

```javascript
return /* @html */`
	<div>hello</div>
`
```

I prefer the pattern like

```regex
(?x)(\\s+?(\\w+\\.)?(\\/\\*\\s@)?(?:html|raw)(\\s\\*\\/)?\\s*)(`)
```

I have set it in my `~/.vscode/extentions`. I do know that the pattern is not very grace for your repository. So maybe a setting for tag pattern can help us set the custom `begin`.

Thanks a lot.

**Comment by KytoSai** [comment]
Good idea , I think this extension should work like you describe

**Comment by jtr109** [comment]
@KytoSai Thx. But a builtin feature is more desirable. 😃

**Comment by mjbvz** [comment]
Try this extension: https://marketplace.visualstudio.com/items?itemName=bierner.comment-tagged-templates

Doesn't add intellisense but handles highlighting

**Comment by jtr109** [comment]
Thanks a lot. I will have a try.
