### ISSUE TITLE
html syntax highlighting in coffeescripts triple quoted strings?

### ISSUE THREAD

**Issue by SaschaMaisel** [mjbvz/vscode-lit-html#27]
Hello dear folks,

is there an easy way to convince vscode-lit-html to perform html-style syntax highlighting in coffeescript's triple quoted multi-line strings?

` 
"""  
    <div class="fieldset">
        <video class="videoPlayer" v-bind:src="player.url" type="video/mp4" controls></video>  
    </div>  
    """ 
`

I've looked a bit through lit-html and I think the functionality shouldn't be so far away from what you guys already offer. Maybe it's just a case of adding a few lines in some json file? 

I understand its a typescript/javascript extension, but it would be supercool if somebody could look into it.

Best,
Sascha

**Comment by mjbvz** [comment]
Supporting coffeescript is out of scope.

You can look through this library to see how the syntax highlighting is implemented using grammar injections. It should be possible to adopt to coffeescript as well but I can't say for sure
