### ISSUE TITLE
Generalize name/description of package

### ISSUE THREAD

**Issue by RasCarlito** [mjbvz/vscode-lit-html#3]
Hi!

Thanks for this vscode plugin. Only one I've found that successfully highlights html in js template strings. Great work! :clap:

Might I suggest to generalize the description or name of the package? It was very hard to find, I had to digg to the bottom of vscode issues on github to find your post about your package (thanks for posting there btw!).

I use choojs as a front-end framework which also uses js template strings for the html. Maybe if the description or key works would contain "html in js template strings" it would be easier to find when searching in vscode packages. I don't even know if that is possible, anyway.

Again awesome work, thank you.
I might soon try to install your intellisens plugin seems awesome aswell :smiley: 

Cheers

**Comment by mjbvz** [comment]
Good idea! I've made some changes to the package.json and readme to hopefully make this more clear. Please submit a PR if you have any ideas on how the description/readme could be further improved
