### ISSUE TITLE
HTML autocomplete not working...

### ISSUE THREAD

**Issue by rchrdnsh** [mjbvz/vscode-lit-html#32]
Not sure if this is an issue for this extension or not, but syntax highlighting is totally working, but autocompletion is acting strange...

<img width="973" alt="screenshot 2018-06-24 22 13 48" src="https://user-images.githubusercontent.com/7884263/41831471-150bf630-77fc-11e8-969c-cf39ef16df63.png">

...so, instead of getting a list of html tags, I seem to be getting a list of, well, words, and nothing more. I'm assuming that the 'abc' icon denotes that it is simply suggesting plain old words in the English language, when all I want is for the autocompletion suggestions to be html tags.

Anyway, again, not sure if this is an issue for this extension, but I'm not sure what to do ¯\\\_(ツ)\_/¯

**Comment by rchrdnsh** [comment]
hmmmm...still not working for me as expected...just to let you know, I'm not using lit-html, I'm using Vue JS, and my hope was that syntax highlighting and autocompletion would work in my use case, which is a key: value pair inside a js object inside a js file. If that is outside of the scope of the this plugin, then no worries :-)

**Comment by justinribeiro** [comment]
It should return in that case; if you use `<` as the start, does it return the html list as in the screenshot below?

![image](https://user-images.githubusercontent.com/643503/42180924-e0b72d12-7ded-11e8-8611-4433d7923ff9.png)

**Comment by abdonrd** [comment]
It also don't work for me:

<img width="845" alt="screen shot 2018-07-02 at 20 49 10" src="https://user-images.githubusercontent.com/1007051/42180944-66adcbba-7e39-11e8-8aea-239ba1ee369a.png">

**Comment by justinribeiro** [comment]
I think the issue is that currently the lang service doesn't return the Emmet suggestions (which don't require the `<` start to populate.

So, you can explicitly set this by changing your vs code prefs with something like:

```js
"emmet.includeLanguages": {
  "typescript": "html",
  "javascript": "html"
}
```

And then what I can do is look at adding explicit support for Emmet in the lang service via `vscode-emmet-helper`.

**Comment by rchrdnsh** [comment]
ahhhhh, yes!!! That has worked! So I did not want IntelliSense then, I wanted emmet instead. And it totally worked, thank you @justinribeiro :-)

**Comment by abdonrd** [comment]
@justinribeiro I just tried but it seems that it doesn't work for me:

![jul-02-2018 23-18-37](https://user-images.githubusercontent.com/1007051/42186818-56181ab6-7e4e-11e8-8e74-d53fb99ddd9a.gif)

**Comment by abdonrd** [comment]
@justinribeiro I don't know why, but today it's working. 😮

**Comment by justinribeiro** [comment]
That's good news because I was having a heck of a time trying to duplicate it. :-)

I'll keep this in the back of my mind though and see where the edge case was.

**Comment by abdonrd** [comment]
@justinribeiro sorry for the wasted time! I think the only different thing I did was turn off the computer yesterday and turn it on again today. 🤔

**Comment by justinribeiro** [comment]
@abdonrd No worries! If it gives you more issues, let me know.

**Comment by mjbvz** [comment]
Closing since it sounds like this issue has been resovled

**Comment by alangdm** [comment]
Just a comment in case someone else has this problem later on, emmet still won't work event after adding the includeLanguages setting if you have the [HTML CSS Support extension](https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css), if you remove/disable that extension it will work

**Comment by tkrns** [comment]
@alangdm yes this plugins causes emmet not to work. Removing HTML CSS Support is one of the solutions.
