### ISSUE TITLE
Request: Please support Vue/other frameworks by changing one line of code.

### ISSUE THREAD

**Issue by David-Else** [mjbvz/vscode-lit-html#38]
Hi,

It has taken a lot of messing about, but now your plugin works as I hoped it would when I first discovered it.
```
 lit-html.json:

"begin": "(`)(?=$|[\\s\\S]*<[a-zA-Z][\\s\\S]*>[\\s\\S]*)",
```
I have no idea why this, or something similar,  would not be default? It should really be an option in vscode itself. Now it works for everything, including Vue:
```

export default {
  name: 'App',
  components: {
    UserList,
  },
  template: `
  <div class="container mx-auto p-4">
     <h1>Users</h1>
    <user-list class="mt-6"></user-list>
  </div>
  `,
};
```

I don't know why this extension is artificially crippled.  I think there is something I don't understand, please help me. There is no decent alternative at the moment, many thanks for making it, I don't mean to come over as angry, but the situation seems so wrong.

**Comment by justinribeiro** [comment]
I won't speak for the project, but the ECMAScript 2015 spec and current [ECMAScript 2019 draft](https://tc39.github.io/ecma262/#sec-static-semantics-templatestrings) states that template literals are strings. It's hard to assume that all template literals are html/css and that a single plugin or editor should parse them all as such, when all the specs says it's that it should be a string and may be something entirely different based on whom the developer is and what they are trying to accomplish.

With tagged literals the case and support becomes more targeted and specific, and helps meet a defined expectation of the developer. We know what the behavior of `html` as a tagged literal needs to be based on what lit-html tells us, and we can parse to that case. When things don't work as expected, we can be specific as to a fix (i.e. a number of the issues that @abdonrd has reported are good examples of developer expectations and have been fixed/polished; much :heart: for find those by the way Abdón).

I'm all for more support, but blanket turning on for all things might lead to confusion where none should exist.

**Comment by David-Else** [comment]
You make a good point. Having a preference inside vs code to switch on highlighting for all template literals that contain a HTML tag would be PERFECT :)

As it stands, having template literals highlighted inside vs code is an incredibly important feature which makes it possible to work without a build step in Vue (and probably many other frameworks). Using `vscode-lit-html` and `IntelliSense for CSS class names in HTML` it is possible to edit the classes in the HTML and get full intellisense, which is an invaluable tool.

I really hope we can get something like a preference switch asap, if more people could use this extension there would be a lot of happy people.

**Comment by justinribeiro** [comment]
Matt did release [Comment tagged templates](https://marketplace.visualstudio.com/items?itemName=bierner.comment-tagged-templates) which adds basic syntax highlighting for JavaScript and TypeScript tagged template strings using a language identifier. This helps cover the initial gap for a lot of potential languages within a template literal, so I'd definitely give that a look.

Other projects are also working on this to meet their framework/library specific needs:

1. VueJs (Vetur) - [Add template literal support](https://github.com/vuejs/vetur/issues/49), [Extract props / data / methods info from Component to power template IntelliSense](https://github.com/vuejs/vetur/issues/145)
2. Angular (Angular2Inline) - [Already has support](https://github.com/natewallace/angular2-inline)

I believe the landscape for support will smooth out, especially as the folks update their language servers, tools are updated, and the wonderful folks working on VS Code add interfaces to do more cool language features. We'll get there. :smiley:

**Comment by David-Else** [comment]
@justinribeiro comment-tagged-templates is perfect, **problem solved.** 

Thanks so much for pointing this out, and thanks Matt Bierner for making it!
