### ISSUE TITLE
CSS in HTML stopped being highlighted as of VSC Version: 1.25.0

### ISSUE THREAD

**Issue by sjmiles** [mjbvz/vscode-lit-html#40]
I'd swear it used to work, but it's possible I'm losing my mind. Apologies if it's the latter.

![image](https://user-images.githubusercontent.com/98045/42403952-0205bf66-813a-11e8-8278-30609745654c.png)

**Comment by sjmiles** [comment]
Fwiw, it works in .html files that contain script nodes that contain html templates, but not in pure .js files.

Is this a problem with my configuration, and nothing to do with vscode-lit-html?

**Comment by mjbvz** [comment]
What other extensions do you have installed?

**Comment by sjmiles** [comment]
`lit-html` just upgraded to 1.6 ... was that there before? In any case, it's all fixed now.

**Comment by sjmiles** [comment]
Btw, thank you for making this extension!
