### ISSUE TITLE
Highlighting attributes breaks when not wrapped with "

### ISSUE THREAD

**Issue by ruphin** [mjbvz/vscode-lit-html#46]
![highlighting-error](https://user-images.githubusercontent.com/66762/44225665-6105d400-a18e-11e8-8591-4e501ba7194f.png)

According to the HTML specifications, attributes do not require to be wrapped in ".

**Comment by ruphin** [comment]
Reported upstream: Microsoft/typescript-lit-html-plugin/issues/18

**Comment by csvn** [comment]
I've encountered this issue as well. The syntax highlighting breaks a lot when using arrow functions and event listeners.

```typescript
html`
  <x-product .data=${ data } @click=${ () => remove('foo') }></x-product>
`;
```

![image](https://user-images.githubusercontent.com/8770194/50156524-4cb61d00-02cf-11e9-81da-a0404ee2f407.png)

**Comment by csvn** [comment]
I tried taking a look at it to see if I could help, but didn't get far. Without quotes the scope for the template expression becomes very wrong, and I guess a custom pattern is required to correctly mark template expressions.

![image](https://user-images.githubusercontent.com/8770194/50156844-1cbb4980-02d0-11e9-9147-4ec4f879ef7c.png)
