### ISSUE TITLE
[Feature Request] Extend to other languages

### ISSUE THREAD

**Issue by mpearon** [mjbvz/vscode-lit-html#47]
Are there any plans to extend this functionality to other languages?
I would love to see syntax highlighting in PowerShell - inside HereStrings, specifically.

Here are the two common PowerShell extensions:
.ps1
.psm1

**Comment by mjbvz** [comment]
Try https://marketplace.visualstudio.com/items?itemName=bierner.comment-tagged-templates

**Comment by mjbvz** [comment]
Nvm, that extension is more for the reverse case of what you want (highlighting powershell strings in JS files) but take a look to see how it uses injection grammars
