### ISSUE TITLE
Possible/easy to enable for ejs templates?

### ISSUE THREAD

**Issue by cheapsteak** [mjbvz/vscode-lit-html#49]
The plugin doesn't currently highlight tagged templates strings in ejs files

```
<div>
  <%- html`<button>` %>
</div>
```

The`<button>` doesn't get syntax highlighting 

Any idea what would go into enabling this? I'd love to help but not sure where to start

**Comment by mjbvz** [comment]
Consider forking this plugin if you need ejs support. It's out of scope for this plugin
