### ISSUE TITLE
Intellisense adding "this" when its already there

### ISSUE THREAD

**Issue by akc42** [mjbvz/vscode-lit-html#51]
I am pretty sure it is this module - I have tried disabling it and trying to cause the issue I describe below and I can't.  When I re-enable this module the problem occurs fairly quickly afterwards - not every time but seems to be a timing issue when typing fast.

The problem...   I am typing something fairly rapidly like
`this.willHaveAProblem = this.shadowRoot.querySelector('#test')`
as I am typing after I have typed `this.` an option for (for instance) `willHaveAProblem` appears as a possibility.  I can either press tab or sometimes have finished typing the complete variable and type a space, but the result I end up with is
`this.this.willHaveAProblem`
that is a double `this`.
It is not every time and its not always the left hand side of an equals, it can be anywhere.

It sometimes seems related to the existence of class methods.  For instance, I am frequently typing something like the following in the constructor because the function is to be called by a lit-html event

`this._myClassMethod = this._myClassMethod.bind(this)`

the intellisense options shown after I have typed the `=` or I have already added the following:
`<some-element @value-changed="${this._myClassMethod}">` somewhere in the render() function

sometimes have both a class property and a class method.  If I select the property the issue never occurs, if I select the class method then it sometimes occurs.

**Comment by mjbvz** [comment]
This should have been fixed by 0.6.0, specifically https://github.com/Microsoft/typescript-lit-html-plugin/commit/1382abc4bf9c177335b80baa0a5971994fe1d8e1
