### ISSUE TITLE
add possibility to use comments /*html*/

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [mjbvz/vscode-lit-html#53]
It would be nice if the extention would also work with comments like so:

```javascript
/*html*/`<div></div>`
```

Instead of only rely on 

```javascript
html`<div></div>`
```

One might use a library that is not named "html".

Thank you for this great plugin!

**Comment by mjbvz** [comment]
This extension should do what you want: https://marketplace.visualstudio.com/items?itemName=bierner.comment-tagged-templates
