### ISSUE TITLE
Highlighting does not work in html files

### ISSUE THREAD

**Issue by pstachula-dev** [mjbvz/vscode-lit-html#55]
After update Visual Studio Code to version 1.29.0, highlighting html is not working.

![bug](https://user-images.githubusercontent.com/230560/48552191-15bba880-e8d8-11e8-9d8b-5c62b244e27e.PNG)

**Comment by ald890** [comment]
It still does not work.

**Comment by mjbvz** [comment]
What other plugins do you have installed? Please share the text of that file too

**Comment by ald890** [comment]
I have to add that literal-string is in the file with the .html extension.

![extensions](https://user-images.githubusercontent.com/230560/48692416-3d5f8900-ebd6-11e8-8fae-5f3ef59dc3a9.PNG)

**Comment by ald890** [comment]
But on the previous version of VS Code highlighting was working correctly.

**Comment by ald890** [comment]
@mjbvz Can you answer why this plugin was working correctly onthe  older version of VS Code? Maybe you can a find simple way to fix this issue.
