### ISSUE TITLE
Support syntax highlighting inside css`` template literal

### ISSUE THREAD

**Issue by kenchris** [mjbvz/vscode-lit-html#60]
The latest LitElement 2.0.0 RC 1 comes with a ``` css`` ``` template literal in order to support static CSS (and constructable stylesheets). The CSS inside this ``` css`` ``` literal doesn't have syntax highlighting

![image](https://user-images.githubusercontent.com/1101339/51026935-f7002800-158f-11e9-8a59-0c0e4bec9628.png)

@justinribeiro @justinfagnani

**Comment by justinribeiro** [comment]
@mjbvz Would you prefer that I add another syntaxes def or update the base def within `syntaxes/lit-html.json` to support `css`?

**Comment by mjbvz** [comment]
Can you just use the VS Code styled plugin for this? It already highlights `css` tagged templates

**Comment by madiodio** [comment]
@kenchris he's talking about this one [vscode-styled-components](https://github.com/styled-components/vscode-styled-components/), it even has auto-completion :).

![screen shot 2019-01-11 at 23 43 58](https://user-images.githubusercontent.com/15022248/51065157-4d568080-15fb-11e9-9f80-5885422a29af.png)

**Comment by mjbvz** [comment]
We could include it as an extension dependency. But would the majority of users of this extension want it included? Im leaning towards having a blurb in the documentation about this instead

**Comment by kenchris** [comment]
I wish the extension had a more generic name than styled components which seems to be a project

**Comment by justinribeiro** [comment]
I think it's a reasonable dependency, given the release candidate (`css` isn't going to go away). Anything to help smooth the development experience (less steps = good).

**Comment by mjbvz** [comment]
I suspect that many people are using this extension for frameworks besides lit-html, which is why I prefer  just documenting that you can get `css` intellisense from the styled components extension. 

We could also put together an [extension pack](https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup) that bundles up all extensions related to lit-html

**Comment by mario-aleo** [comment]
Shouldn't "lit-html.tags" configuration do the trick? If it should, it's not working :(

**Comment by motss** [comment]
I think it only does when you wrap the content inside a `style` tag.

**Comment by mjbvz** [comment]
Closing as external
