### ISSUE TITLE
Support css syntax highlighting in template literal

### ISSUE THREAD

**Issue by dustensalinas** [mjbvz/vscode-lit-html#66]
For example:

```
class MyElement extends LitElement {
  static styles = css`
    :host {
      display: block;
    }
  `;
}
```

Adding css to the literal tags setting works great but unfortunately does not perform css syntax highlighting without the <style tag>.  We'll see if I'm able to get to this myself and do a PR but wanted to know any thoughts or in progress work on this if there was any.

**Comment by mjbvz** [comment]
Duplicate of #60

Install https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components for this

**Comment by Anthony-As** [comment]
muchas gracias por tu aporte
