### ISSUE TITLE
Conflict - 'Babel ES6/ES7' Extension (dzannotti.vscode-babel-coloring)

### ISSUE THREAD

**Issue by alinasrabadi** [mjbvz/vscode-lit-html#67]
There is conflict between this extension and 'Babel ES6/ES7' (dzannotti.vscode-babel-coloring).
VsCode Version: 1.28.2

**Comment by mjbvz** [comment]
Yes, don't use both extensions at the same time

**Comment by AliMD** [comment]
@mjbvz 
Wow, Awesome support with awesome solution :confused:
