### ISSUE TITLE
Is there a configuration Option for <script> Tags inside .html files

### ISSUE THREAD

**Issue by lucasoertli** [mjbvz/vscode-lit-html#86]
Hi 
We write a lot of inline JavaScript in html Files. Is there a possibility to configure the plugin to work also with .html files?
Thank you very mutch.

**Comment by pupu61509** [comment]
hi
it's easy to add highlight for html without intellisense.

optional 1. install vsce `npm i vsce -g`
2. clone or unzip vscode-lit-html
3. `yarn` or `npm i`
4. modify package.json, find all `"injectTo"` and add `"text.html.derivative"` below `"text.html.basic"`.
![image](https://user-images.githubusercontent.com/10653240/115321351-3463af00-a1b6-11eb-86b8-d8b43792525a.png)
5. save and build vsix with `vsce package`
6. install vsix.
7. html highlight works.
![image](https://user-images.githubusercontent.com/10653240/115321204-eea6e680-a1b5-11eb-800a-30331e48f2f1.png)

**Comment by lucasoertli** [comment]
Thank you very mutch, it worked :)

**Comment by changbowen** [comment]
FYI I had to add `text.aspnetcorerazor` for the `<script>` tags under `cshtml` files to work.
