### ISSUE TITLE
Publish to npm (or change package name to "vscode-lit-html")

### ISSUE THREAD

**Issue by justinfagnani** [mjbvz/vscode-lit-html#90]
Depending on this package form another extension, as done in lit-plugin, is difficult because it must be added as a Git dependency and must be installed as `lit-html` since the package name here is `lit-html`. This prevents installing the actual `lit-html` in the same package.

Could we publish this as `vscode-lit-html` on npm to fix that?

**Comment by mjbvz** [comment]
VS Code extensions generally aren't published to npm

**Comment by justinfagnani** [comment]
I understand that, but there is useful code in here, being used in lit-plugin (dependency [here](https://github.com/runem/lit-analyzer/blob/master/packages/vscode-lit-plugin/package.json#L37), usage [here](https://github.com/runem/lit-analyzer/blob/master/packages/vscode-lit-plugin/package.json#L648), etc).

The current way to get the code is with a GitHub dependency, but as I said the package name here conflicts with the actual `lit-html` package.

**Comment by mjbvz** [comment]
What code are you consuming from this project?

**Comment by justinfagnani** [comment]
The syntax definitions: https://github.com/runem/lit-analyzer/blob/master/packages/vscode-lit-plugin/package.json#L648

**Comment by mjbvz** [comment]
A git dependency seems fine for such a specialized use case. Plus I don't want the overhead of publishing to npm or thinking about semantic versioning or any of that
